// src/routes/react/Components/CartCard.jsx
import { React, useState } from "react";

export default function CartCard({ auth, title, amount }) {
    const [quantity, setQuantity] = useState(amount);
    const increase = () => {
        setQuantity((quantity) => quantity + 1);
    };
    const decrease = () => {
        quantity > 0 ? setQuantity((quantity) => quantity - 1) : setQuantity(0);
    };

    return (
        <>
            <div className="flex flex-row justify-between bg-white rounded-lg p-6 shadow-[0px_14px_34px_0px_rgba(0,0,0,0.08)]">
                <div className="flex flex-col">
                    <p className="text-black text-xl">{title}</p>
                </div>

                <div className="flex flex-row justify-center items-center ml-2">
                    <div className="h-min w-max rounded-lg border border-gray-800 overflow-clip">
                        <button className="bg-gray-200 w-6" onClick={decrease}>
                            -
                        </button>
                        <input
                            type="text"
                            value={quantity}
                            onChange={(change) => {
                                !isNaN(change.target.value)
                                    ? setQuantity(change.target.value)
                                    : "";
                                console.log(typeof change.target.value);
                            }}
                            className="w-8 p-0 text-center bg-white border border-gray-800 border-y-0"
                        />
                        <button className="bg-gray-200 w-6" onClick={increase}>
                            +
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
}

// src/lib/components/CartCard.svelte
<script lang="ts">
	export let title: string;
	export let description: string;

	export let quantity: number = 0;
</script>

<div
	class="flex flex-row justify-between bg-white rounded-lg p-6 shadow-[0px_14px_34px_0px_rgba(0,0,0,0.08)]"
>
	<div class="flex flex-col">
		<p class="text-black text-xl">{title}</p>
		<p class="text-sm pt-4">{description}</p>
	</div>

	<div class="flex flex-col justify-center items-center ml-2">
		<div
			class="flex flex-row justify-center items-center h-min w-max rounded-lg border border-gray-800 overflow-clip"
		>
			<button
				class="bg-gray-200 w-6"
				on:click={() => {
					quantity > 0 ? (quantity -= 1) : (quantity = 0);
				}}
			>
				-
			</button>
			<input
				type="number"
				bind:value={quantity}
				class="w-8 p-0 text-center bg-white border border-gray-800 border-y-0"
			/>
			<button
				class="bg-gray-200 w-6"
				on:click={() => {
					quantity += 1;
				}}
			>
				+
			</button>
		</div>
		<p class="text-xs mt-1">gallons</p>
	</div>
</div>

<style>
	input[type='number']::-webkit-outer-spin-button,
	input[type='number']::-webkit-inner-spin-button {
		-webkit-appearance: none;
		margin: 0;
	}

	input[type='number'] {
		appearance: textfield;
		-moz-appearance: textfield;
	}
</style>
